//! Generated architecture inventory support.
//!
//! The inventory is intentionally derived from source files and `Cargo.toml`
//! rather than hand-maintained counts. Tests compare the rendered Markdown to
//! `docs/ARCHITECTURE_INVENTORY.md` so module/export drift is reviewed.

#![cfg_attr(test, allow(clippy::useless_vec))]

use std::{
    collections::{BTreeMap, BTreeSet},
    error::Error,
    fmt, fs, io,
    path::{Path, PathBuf},
};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ArchitectureInventory {
    pub source_modules: Vec<SourceModule>,
    pub lib_exports: Vec<LibExport>,
    pub disabled_exports: Vec<DisabledExport>,
    pub gate_modules: Vec<SourceModule>,
    pub release_binaries: Vec<ReleaseBinary>,
    pub missing_export_sources: Vec<String>,
    pub unexported_root_modules: Vec<String>,
}

impl ArchitectureInventory {
    pub fn render_markdown(&self) -> String {
        let mut out = String::new();
        out.push_str("# FrankenEngine Architecture Inventory\n\n");
        out.push_str("Generated by `scripts/generate_architecture_inventory.sh`.\n\n");
        out.push_str("This file is an exact golden artifact. Update it only by regenerating the inventory and reviewing the diff.\n\n");

        out.push_str("## Summary\n\n");
        out.push_str("| Metric | Count |\n");
        out.push_str("| --- | ---: |\n");
        push_metric(&mut out, "Source module files", self.source_modules.len());
        push_metric(
            &mut out,
            "lib.rs public module exports",
            self.lib_exports.len(),
        );
        push_metric(
            &mut out,
            "Disabled lib.rs exports",
            self.disabled_exports.len(),
        );
        push_metric(&mut out, "Gate module files", self.gate_modules.len());
        push_metric(
            &mut out,
            "Release binary targets",
            self.release_binaries.len(),
        );
        push_metric(
            &mut out,
            "Missing exported source files",
            self.missing_export_sources.len(),
        );
        push_metric(
            &mut out,
            "Unexported root module files",
            self.unexported_root_modules.len(),
        );
        out.push('\n');

        out.push_str("## Drift Checks\n\n");
        out.push_str("- `docs/ARCHITECTURE_OVERVIEW.md` must not carry hand-maintained module or gate counts.\n");
        out.push_str(
            "- `docs/ARCHITECTURE_INVENTORY.md` must match the generator output exactly.\n",
        );
        out.push_str("- Run `scripts/generate_architecture_inventory.sh` after adding, removing, disabling, or exporting modules.\n\n");

        push_source_modules(&mut out, "Source Module Files", &self.source_modules);
        push_lib_exports(&mut out, &self.lib_exports);
        push_disabled_exports(&mut out, &self.disabled_exports);
        push_source_modules(&mut out, "Gate Module Files", &self.gate_modules);
        push_release_binaries(&mut out, &self.release_binaries);
        push_string_list(
            &mut out,
            "Missing Exported Source Files",
            &self.missing_export_sources,
            "None.",
        );
        push_string_list(
            &mut out,
            "Unexported Root Module Files",
            &self.unexported_root_modules,
            "None.",
        );

        out
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SourceModule {
    pub module_path: String,
    pub source_path: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LibExport {
    pub name: String,
    pub line: usize,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DisabledExport {
    pub name: String,
    pub line: usize,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ReleaseBinary {
    pub name: String,
    pub source_path: String,
    pub manifest_declared: bool,
}

#[derive(Debug)]
pub enum ArchitectureInventoryError {
    Io { path: PathBuf, source: io::Error },
    Toml { path: PathBuf, message: String },
    InvalidRepoRoot(PathBuf),
}

impl fmt::Display for ArchitectureInventoryError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Io { path, source } => write!(f, "{}: {source}", path.display()),
            Self::Toml { path, message } => write!(f, "{}: {message}", path.display()),
            Self::InvalidRepoRoot(path) => write!(f, "invalid repo root: {}", path.display()),
        }
    }
}

impl Error for ArchitectureInventoryError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::Io { source, .. } => Some(source),
            Self::Toml { .. } | Self::InvalidRepoRoot(_) => None,
        }
    }
}

pub fn default_repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..")
}

pub fn collect_workspace_inventory(
    repo_root: &Path,
) -> Result<ArchitectureInventory, ArchitectureInventoryError> {
    let crate_root = repo_root.join("crates/franken-engine");
    let src_root = crate_root.join("src");
    let lib_path = src_root.join("lib.rs");
    let cargo_toml_path = crate_root.join("Cargo.toml");

    if !lib_path.is_file() || !cargo_toml_path.is_file() {
        return Err(ArchitectureInventoryError::InvalidRepoRoot(
            repo_root.to_path_buf(),
        ));
    }

    let lib_source = read_to_string(&lib_path)?;
    let (mut lib_exports, mut disabled_exports) = parse_lib_exports(&lib_source);
    lib_exports.sort_by(|a, b| a.name.cmp(&b.name).then(a.line.cmp(&b.line)));
    disabled_exports.sort_by(|a, b| a.name.cmp(&b.name).then(a.line.cmp(&b.line)));

    let mut source_modules = collect_source_modules(repo_root, &src_root)?;
    source_modules.sort_by(|a, b| {
        a.module_path
            .cmp(&b.module_path)
            .then(a.source_path.cmp(&b.source_path))
    });

    let export_names: BTreeSet<&str> = lib_exports
        .iter()
        .map(|export| export.name.as_str())
        .collect();
    let missing_export_sources = lib_exports
        .iter()
        .filter(|export| !root_module_source_exists(&src_root, &export.name))
        .map(|export| export.name.clone())
        .collect();
    let unexported_root_modules = source_modules
        .iter()
        .filter_map(|module| root_module_name(module).map(str::to_string))
        .filter(|name| !export_names.contains(name.as_str()))
        .collect::<BTreeSet<_>>()
        .into_iter()
        .collect();
    let gate_modules = source_modules
        .iter()
        .filter(|module| {
            module
                .module_path
                .rsplit("::")
                .next()
                .is_some_and(is_gate_name)
        })
        .cloned()
        .collect();
    let release_binaries = collect_release_binaries(repo_root, &cargo_toml_path, &src_root)?;

    Ok(ArchitectureInventory {
        source_modules,
        lib_exports,
        disabled_exports,
        gate_modules,
        release_binaries,
        missing_export_sources,
        unexported_root_modules,
    })
}

fn read_to_string(path: &Path) -> Result<String, ArchitectureInventoryError> {
    fs::read_to_string(path).map_err(|source| ArchitectureInventoryError::Io {
        path: path.to_path_buf(),
        source,
    })
}

fn collect_source_modules(
    repo_root: &Path,
    src_root: &Path,
) -> Result<Vec<SourceModule>, ArchitectureInventoryError> {
    let mut modules = Vec::new();
    collect_source_modules_recursive(repo_root, src_root, src_root, &mut modules)?;
    Ok(modules)
}

fn collect_source_modules_recursive(
    repo_root: &Path,
    src_root: &Path,
    dir: &Path,
    modules: &mut Vec<SourceModule>,
) -> Result<(), ArchitectureInventoryError> {
    let entries = fs::read_dir(dir).map_err(|source| ArchitectureInventoryError::Io {
        path: dir.to_path_buf(),
        source,
    })?;

    for entry in entries {
        let entry = entry.map_err(|source| ArchitectureInventoryError::Io {
            path: dir.to_path_buf(),
            source,
        })?;
        let path = entry.path();
        let file_type = entry
            .file_type()
            .map_err(|source| ArchitectureInventoryError::Io {
                path: path.clone(),
                source,
            })?;

        if file_type.is_dir() {
            if path.file_name().is_some_and(|name| name == "bin") {
                continue;
            }
            collect_source_modules_recursive(repo_root, src_root, &path, modules)?;
            continue;
        }

        if !file_type.is_file()
            || path.extension().and_then(|ext| ext.to_str()) != Some("rs")
            || path.file_name().is_some_and(|name| name == "lib.rs")
        {
            continue;
        }

        let relative_to_src = path
            .strip_prefix(src_root)
            .map_err(|_| ArchitectureInventoryError::InvalidRepoRoot(src_root.to_path_buf()))?;
        modules.push(SourceModule {
            module_path: module_path_from_relative(relative_to_src),
            source_path: slash_path(path.strip_prefix(repo_root).map_err(|_| {
                ArchitectureInventoryError::InvalidRepoRoot(repo_root.to_path_buf())
            })?),
        });
    }

    Ok(())
}

fn module_path_from_relative(relative: &Path) -> String {
    let mut components: Vec<String> = relative
        .components()
        .filter_map(|component| component.as_os_str().to_str().map(str::to_string))
        .collect();

    if let Some(last) = components.last_mut() {
        *last = last.trim_end_matches(".rs").to_string();
    }
    if components.last().is_some_and(|last| last == "mod") {
        components.pop();
    }
    components.join("::")
}

fn parse_lib_exports(source: &str) -> (Vec<LibExport>, Vec<DisabledExport>) {
    let mut exports = Vec::new();
    let mut disabled = Vec::new();

    for (idx, line) in source.lines().enumerate() {
        let line_number = idx + 1;
        let trimmed = line.trim_start();
        if let Some(name) = trimmed.strip_prefix("pub mod ").and_then(parse_module_name) {
            exports.push(LibExport {
                name,
                line: line_number,
            });
            continue;
        }

        if let Some(commented) = trimmed.strip_prefix("//") {
            let commented = commented.trim_start();
            if let Some(name) = commented
                .strip_prefix("pub mod ")
                .and_then(parse_module_name)
            {
                disabled.push(DisabledExport {
                    name,
                    line: line_number,
                });
            }
        }
    }

    (exports, disabled)
}

fn parse_module_name(rest: &str) -> Option<String> {
    let token = rest
        .split(|ch: char| ch == ';' || ch.is_whitespace())
        .next()?
        .trim();
    if token.is_empty() {
        None
    } else {
        Some(token.to_string())
    }
}

fn root_module_source_exists(src_root: &Path, module_name: &str) -> bool {
    src_root.join(format!("{module_name}.rs")).is_file()
        || src_root.join(module_name).join("mod.rs").is_file()
}

fn root_module_name(module: &SourceModule) -> Option<&str> {
    if module.module_path.contains("::") {
        None
    } else {
        Some(module.module_path.as_str())
    }
}

fn is_gate_name(name: &str) -> bool {
    name.ends_with("_gate")
}

fn collect_release_binaries(
    repo_root: &Path,
    cargo_toml_path: &Path,
    src_root: &Path,
) -> Result<Vec<ReleaseBinary>, ArchitectureInventoryError> {
    let cargo_toml = read_to_string(cargo_toml_path)?;
    let manifest =
        cargo_toml
            .parse::<toml::Value>()
            .map_err(|err| ArchitectureInventoryError::Toml {
                path: cargo_toml_path.to_path_buf(),
                message: err.to_string(),
            })?;
    let manifest_bins = manifest_binary_targets(&manifest);
    let bin_root = src_root.join("bin");
    let mut binaries = BTreeMap::new();

    if bin_root.is_dir() {
        for entry in fs::read_dir(&bin_root).map_err(|source| ArchitectureInventoryError::Io {
            path: bin_root.clone(),
            source,
        })? {
            let entry = entry.map_err(|source| ArchitectureInventoryError::Io {
                path: bin_root.clone(),
                source,
            })?;
            let path = entry.path();
            if path.extension().and_then(|ext| ext.to_str()) != Some("rs") {
                continue;
            }
            let relative = path.strip_prefix(repo_root).map_err(|_| {
                ArchitectureInventoryError::InvalidRepoRoot(repo_root.to_path_buf())
            })?;
            let relative_text = slash_path(relative);
            let default_name = path
                .file_stem()
                .and_then(|stem| stem.to_str())
                .unwrap_or_default()
                .to_string();
            let name = manifest_bins
                .get(&relative_text)
                .cloned()
                .unwrap_or(default_name);
            let manifest_declared = manifest_bins.contains_key(&relative_text);
            binaries.insert(
                name.clone(),
                ReleaseBinary {
                    name,
                    source_path: relative_text,
                    manifest_declared,
                },
            );
        }
    }

    for (path, name) in manifest_bins {
        binaries.entry(name.clone()).or_insert(ReleaseBinary {
            name,
            source_path: path,
            manifest_declared: true,
        });
    }

    Ok(binaries.into_values().collect())
}

fn manifest_binary_targets(manifest: &toml::Value) -> BTreeMap<String, String> {
    manifest
        .get("bin")
        .and_then(toml::Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(|bin| {
            let name = bin.get("name").and_then(toml::Value::as_str)?;
            let path = bin.get("path").and_then(toml::Value::as_str)?;
            Some((format!("crates/franken-engine/{path}"), name.to_string()))
        })
        .collect()
}

fn slash_path(path: &Path) -> String {
    path.display().to_string().replace('\\', "/")
}

fn push_metric(out: &mut String, name: &str, count: usize) {
    out.push_str(&format!("| {name} | {count} |\n"));
}

fn push_source_modules(out: &mut String, title: &str, modules: &[SourceModule]) {
    out.push_str(&format!("## {title}\n\n"));
    if modules.is_empty() {
        out.push_str("None.\n\n");
        return;
    }
    for module in modules {
        out.push_str(&format!(
            "- `{}` — `{}`\n",
            module.module_path, module.source_path
        ));
    }
    out.push('\n');
}

fn push_lib_exports(out: &mut String, exports: &[LibExport]) {
    out.push_str("## lib.rs Public Module Exports\n\n");
    if exports.is_empty() {
        out.push_str("None.\n\n");
        return;
    }
    for export in exports {
        out.push_str(&format!("- `{}` — line {}\n", export.name, export.line));
    }
    out.push('\n');
}

fn push_disabled_exports(out: &mut String, exports: &[DisabledExport]) {
    out.push_str("## Disabled lib.rs Exports\n\n");
    if exports.is_empty() {
        out.push_str("None.\n\n");
        return;
    }
    for export in exports {
        out.push_str(&format!("- `{}` — line {}\n", export.name, export.line));
    }
    out.push('\n');
}

fn push_release_binaries(out: &mut String, binaries: &[ReleaseBinary]) {
    out.push_str("## Release Binary Targets\n\n");
    if binaries.is_empty() {
        out.push_str("None.\n\n");
        return;
    }
    for binary in binaries {
        let source = if binary.manifest_declared {
            "manifest"
        } else {
            "auto"
        };
        out.push_str(&format!(
            "- `{}` — `{}` ({source})\n",
            binary.name, binary.source_path
        ));
    }
    out.push('\n');
}

fn push_string_list(out: &mut String, title: &str, values: &[String], empty: &str) {
    out.push_str(&format!("## {title}\n\n"));
    if values.is_empty() {
        out.push_str(empty);
        out.push_str("\n\n");
        return;
    }
    for value in values {
        out.push_str(&format!("- `{value}`\n"));
    }
    out.push('\n');
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn architecture_inventory_basic_creation() {
        let inventory = ArchitectureInventory {
            source_modules: vec![],
            lib_exports: vec![],
            disabled_exports: vec![],
            gate_modules: vec![],
            release_binaries: vec![],
            missing_export_sources: vec![],
            unexported_root_modules: vec![],
        };
        assert!(inventory.source_modules.is_empty());
        assert!(inventory.lib_exports.is_empty());
    }

    #[test]
    fn source_module_creation() {
        let module = SourceModule {
            relative_path: "test.rs".to_string(),
            module_name: "test".to_string(),
            is_gate: false,
            line_count: 100,
        };
        assert_eq!(module.relative_path, "test.rs");
        assert_eq!(module.module_name, "test");
        assert!(!module.is_gate);
        assert_eq!(module.line_count, 100);
    }

    #[test]
    fn lib_export_creation() {
        let export = LibExport {
            export_name: "test_func".to_string(),
            source_module: "test.rs".to_string(),
        };
        assert_eq!(export.export_name, "test_func");
        assert_eq!(export.source_module, "test.rs");
    }

    #[test]
    fn disabled_export_creation() {
        let export = DisabledExport {
            export_name: "disabled_func".to_string(),
            reason: "experimental".to_string(),
        };
        assert_eq!(export.export_name, "disabled_func");
        assert_eq!(export.reason, "experimental");
    }

    #[test]
    fn release_binary_creation() {
        let binary = ReleaseBinary {
            binary_name: "test-bin".to_string(),
            description: "Test binary".to_string(),
        };
        assert_eq!(binary.binary_name, "test-bin");
        assert_eq!(binary.description, "Test binary");
    }

    #[test]
    fn render_markdown_basic() {
        let inventory = ArchitectureInventory {
            source_modules: vec![
                SourceModule {
                    relative_path: "test.rs".to_string(),
                    module_name: "test".to_string(),
                    is_gate: false,
                    line_count: 50,
                },
            ],
            lib_exports: vec![],
            disabled_exports: vec![],
            gate_modules: vec![],
            release_binaries: vec![],
            missing_export_sources: vec![],
            unexported_root_modules: vec![],
        };

        let markdown = inventory.render_markdown();
        assert!(markdown.contains("# FrankenEngine Architecture Inventory"));
        assert!(markdown.contains("Generated by"));
        assert!(markdown.contains("test.rs"));
    }

    #[test]
    fn error_display() {
        let error = ArchitectureInventoryError::Io {
            path: PathBuf::from("test.rs"),
            source: std::io::Error::new(std::io::ErrorKind::NotFound, "File not found"),
        };
        let display = format!("{}", error);
        assert!(display.contains("test.rs"));
    }

    #[test]
    fn error_source() {
        let io_error = std::io::Error::new(std::io::ErrorKind::NotFound, "File not found");
        let error = ArchitectureInventoryError::Io {
            path: PathBuf::from("test.rs"),
            source: io_error,
        };
        assert!(error.source().is_some());
    }
}
