#!/usr/bin/env python3
"""Verify the repo's structural-inventory claims against the tree. Fail closed on drift.

Two surfaces, both measured directly from the tree:

* **README.md** -- hand-written counts (modules, tests, scripts, docs, fuzz targets).
* **docs/ARCHITECTURE_INVENTORY.md** -- generated by `franken-architecture-inventory`,
  and self-described as "an exact golden artifact" that nothing enforced. It reported
  495 source modules from April until 2026-07-26 while the tree carried 621. The
  generator's own `--check` would have caught it, but running that means compiling the
  engine crate, and a gate nobody can afford to run is not a gate.

Why (BRIDGE-00.8 item 3)
------------------------
The claim-to-proof matrix governs *capability* wording. Nothing governed *inventory*
wording, so the README architecture tables drifted for two months unnoticed: 495
modules against a real 615, `baseline_interpreter.rs` described as ~31,914 LoC against
a real 98,924, and three named source modules that do not exist at all. A reader who
followed the README to those filenames found nothing.

Regenerating the numbers once fixes the symptom, not the cause. Two days after the
last correction the tree had already moved again (integration tests 1,637 -> 1,649,
gate scripts 292 -> 293, docs 724 -> 726, beads 4,443 -> 4,447). Inventory truth needs
the same treatment as capability truth: enumerable, generated, and gated.

This is the gap-inventory pattern the runtime already uses for `parser_gap_inventory`
and `lowering_gap_inventory` — if something is claimed, it must be measurable, and the
gate must fail closed when the claim drifts from the measurement.

Exact equality is deliberate. A tolerance would mean choosing a threshold below which
the README is allowed to be wrong, and there is no such number for a count that a
generator can produce exactly.

`--fix` rewrites the numbers in place, so complying is one command rather than a
reason to bypass the gate. It only substitutes digits inside existing lines, never
adds or removes any, because `docs/claim_to_proof_matrix_v1.json` pins README claim
spans by line number and a reflow would silently shift every span below the edit.

Usage
-----
    python3 scripts/check_readme_inventory.py [--json PATH] [--fix]
                                              [--section all|readme|inventory-doc]
                                              [--repo-root DIR]

`--fix` covers README rows only. The inventory doc is generator output; the remedy
for its drift is `scripts/generate_architecture_inventory.sh`, not an edit.

Negative drill: `scripts/e2e/architecture_inventory_gate_drift.sh`.

Exit codes
----------
    0  every counted surface matches (or --fix applied the corrections)
    1  drift detected
    2  a row could not be parsed (the format moved; the gate is not silently
       narrowing its own coverage)
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
README = REPO / "README.md"
INVENTORY_DOC = REPO / "docs/ARCHITECTURE_INVENTORY.md"
SRC = REPO / "crates/franken-engine/src"


def set_repo_root(root: Path) -> None:
    """Point every path this gate reads at `root`.

    Exists so the negative drill can run the real guard against a synthetic tree
    instead of a copy of it. A guard that can only ever inspect one hard-coded
    directory cannot be shown to fail closed, and an unfalsifiable guard is
    indistinguishable from one that always returns 0.
    """
    global REPO, README, INVENTORY_DOC, SRC
    REPO = root.resolve()
    README = REPO / "README.md"
    INVENTORY_DOC = REPO / "docs/ARCHITECTURE_INVENTORY.md"
    SRC = REPO / "crates/franken-engine/src"


@dataclass
class Surface:
    key: str
    # Regex with exactly one capture group holding the number to check. Anchored on
    # enough surrounding prose that it cannot match a different row by accident.
    pattern: str
    measure: str  # human description of how the truth is computed
    value: int
    # Advisory rows are reported and corrected by --fix but do not fail the gate.
    #
    # Reserved for counts that move through routine traffic rather than deliberate
    # engineering acts. The bead ledger is the only one: every `br update` across
    # every agent changes it, many times a day, so gating it hard would keep the
    # gate red for reasons no README edit can durably fix. A gate that is always
    # red gets bypassed, and then the eleven rows that DO track real structural
    # change stop being enforced too. Everything else here moves only when somebody
    # adds a module, script, doc, test, or fuzz target.
    advisory: bool = False


def _count_files(rel: str, pattern: str, maxdepth1: bool = True) -> int:
    base = REPO / rel
    if not base.is_dir():
        return 0
    globber = base.glob if maxdepth1 else base.rglob
    return sum(1 for p in globber(pattern) if p.is_file())


def measure() -> list[Surface]:
    src = REPO / "crates/franken-engine/src"
    lib_rs = src / "lib.rs"
    baseline = src / "baseline_interpreter.rs"

    pub_mod = 0
    if lib_rs.is_file():
        pub_mod = sum(
            1 for line in lib_rs.read_text().splitlines() if line.startswith("pub mod ")
        )

    baseline_loc = 0
    if baseline.is_file():
        baseline_loc = len(baseline.read_bytes().split(b"\n")) - 1

    beads = REPO / ".beads/issues.jsonl"
    bead_records = 0
    if beads.is_file():
        bead_records = sum(1 for line in beads.read_text().splitlines() if line.strip())

    docs = REPO / "docs"
    docs_top = 0
    if docs.is_dir():
        docs_top = sum(
            1 for p in docs.iterdir() if p.is_file() and p.suffix in (".md", ".json")
        )

    return [
        Surface(
            "src_modules",
            r"\| Source modules in `crates/franken-engine/src/` \| ([\d,]+) top-level",
            "top-level .rs files in crates/franken-engine/src/",
            _count_files("crates/franken-engine/src", "*.rs"),
        ),
        Surface(
            "pub_mod",
            r"top-level `\.rs` files / ([\d,]+) `pub mod` declarations",
            "lines starting `pub mod ` in lib.rs",
            pub_mod,
        ),
        Surface(
            "baseline_loc",
            r"`baseline_interpreter\.rs` alone is ~[\d.]+ MB / ([\d,]+) LoC",
            "line count of baseline_interpreter.rs",
            baseline_loc,
        ),
        Surface(
            "bin_files",
            r"\| Internal operator binaries in `crates/franken-engine/src/bin/` \| ([\d,]+) `\.rs` files",
            "top-level .rs files in crates/franken-engine/src/bin/",
            _count_files("crates/franken-engine/src/bin", "*.rs"),
        ),
        Surface(
            "integration_tests",
            r"\| Integration tests in `crates/franken-engine/tests/` \| ([\d,]+) top-level files",
            "top-level files in crates/franken-engine/tests/",
            sum(1 for p in (REPO / "crates/franken-engine/tests").iterdir() if p.is_file())
            if (REPO / "crates/franken-engine/tests").is_dir()
            else 0,
        ),
        Surface(
            "rgc_gate_tests",
            r"top-level files \(([\d,]+) are RGC gate tests\)",
            "crates/franken-engine/tests/rgc_*.rs",
            _count_files("crates/franken-engine/tests", "rgc_*.rs"),
        ),
        Surface(
            "gate_scripts",
            r"\| Operator gate scripts in `scripts/run_\*\.sh` \| ([\d,]+) ",
            "scripts/run_*.sh",
            _count_files("scripts", "run_*.sh"),
        ),
        Surface(
            "replay_wrappers",
            r"\| Replay wrappers in `scripts/e2e/\*_replay\.sh` \| ([\d,]+) ",
            "scripts/e2e/*_replay.sh",
            _count_files("scripts/e2e", "*_replay.sh"),
        ),
        Surface(
            "docs_top_level",
            r"\| Architecture / contract docs in `docs/` \| ([\d,]+) top-level files",
            "top-level *.md and *.json in docs/",
            docs_top,
        ),
        Surface(
            "bead_records",
            r"\| Tracked beads in `\.beads/issues\.jsonl` \| ([\d,]+) records",
            "non-blank lines in .beads/issues.jsonl",
            bead_records,
            advisory=True,
        ),
        Surface(
            "fuzz_top",
            r"across two trees: ([\d,]+) in top-level `fuzz/fuzz_targets/`",
            "fuzz/fuzz_targets/*.rs",
            _count_files("fuzz/fuzz_targets", "*.rs"),
        ),
        Surface(
            "fuzz_crate",
            r"\+ ([\d,]+) in `crates/franken-engine/fuzz/fuzz_targets/`",
            "crates/franken-engine/fuzz/fuzz_targets/*.rs",
            _count_files("crates/franken-engine/fuzz/fuzz_targets", "*.rs"),
        ),
    ]


def fmt(value: int) -> str:
    """Match the README's thousands separators so --fix is a pure digit swap."""
    return f"{value:,}"


# --------------------------------------------------------------------------
# docs/ARCHITECTURE_INVENTORY.md
#
# The README rows above are hand-written and gated against the tree. The
# inventory doc is the opposite: fully generated by `franken-architecture-inventory`
# and declared "an exact golden artifact" in its own header -- and nothing enforced
# that. It reported 495 source modules from April until 2026-07-26 while the tree
# carried 621, so the generated companion rotted for three months in a repo whose
# whole discipline is that drift must fail closed.
#
# The generator's own `--check` mode would have caught it, but running it means
# compiling the engine crate, which needs the /dp siblings and tens of minutes. A
# gate nobody can afford to run is not a gate. These checks re-measure the tree
# directly, in the same pure-Python job that already gates the README, so the doc
# cannot silently age again.
#
# This measures the filesystem rather than diffing against generator output, for
# the same reason the README rows do: an independent measurement catches a
# generator that is itself wrong or, as happened here, one that was compiled
# against a different tree entirely and reported on that one instead.
# --------------------------------------------------------------------------


def _module_path(rel: Path) -> str:
    parts = list(rel.parts)
    parts[-1] = parts[-1].removesuffix(".rs")
    if parts[-1] == "mod":
        parts.pop()
    return "::".join(parts)


def measure_inventory() -> dict:
    """Recompute what the generator reports, from the tree."""
    modules: dict[str, str] = {}
    if SRC.is_dir():
        for path in SRC.rglob("*.rs"):
            rel = path.relative_to(SRC)
            if rel.parts[0] == "bin" or path.name == "lib.rs":
                continue
            modules[_module_path(rel)] = (
                path.relative_to(REPO).as_posix()
            )

    exports: list[tuple[str, int]] = []
    disabled: list[tuple[str, int]] = []
    lib_rs = SRC / "lib.rs"
    if lib_rs.is_file():
        for number, line in enumerate(lib_rs.read_text().splitlines(), 1):
            stripped = line.lstrip()
            if stripped.startswith("pub mod "):
                name = re.split(r"[;\s]", stripped[len("pub mod ") :])[0].strip()
                if name:
                    exports.append((name, number))
            elif stripped.startswith("//"):
                commented = stripped[2:].lstrip()
                if commented.startswith("pub mod "):
                    name = re.split(r"[;\s]", commented[len("pub mod ") :])[0].strip()
                    if name:
                        disabled.append((name, number))

    export_names = {name for name, _ in exports}
    root_modules = {m for m in modules if "::" not in m}
    gates = {m: p for m, p in modules.items() if m.rsplit("::", 1)[-1].endswith("_gate")}

    return {
        "modules": modules,
        "exports": exports,
        "disabled": disabled,
        "gates": gates,
        # Both spellings of a root module count. `control_plane` and `sme` are
        # directories with a `mod.rs`, not `<name>.rs` files; treating only the flat
        # form as real would report two phantom "missing" entries.
        "missing_export_sources": sorted(
            n
            for n in export_names
            if not (SRC / f"{n}.rs").is_file() and not (SRC / n / "mod.rs").is_file()
        ),
        "unexported_root_modules": sorted(root_modules - export_names),
    }


def _doc_section(text: str, title: str) -> list[str] | None:
    """Bullet lines of one `## <title>` section; [] for an explicit `None.`."""
    match = re.search(
        rf"^## {re.escape(title)}\n\n(.*?)(?=^## |\Z)", text, re.S | re.M
    )
    if match is None:
        return None
    body = match.group(1)
    if body.strip() == "None.":
        return []
    return [line for line in body.splitlines() if line.startswith("- ")]


def check_inventory_doc() -> tuple[list[dict], bool]:
    """Compare the generated inventory doc to the tree. Returns (rows, parse_failed)."""
    if not INVENTORY_DOC.is_file():
        return [{"surface": "inventory_doc", "status": "unparsed",
                 "measure": "docs/ARCHITECTURE_INVENTORY.md is missing"}], True

    text = INVENTORY_DOC.read_text()
    truth = measure_inventory()
    rows: list[dict] = []
    parse_failed = False

    # `name — path` (source modules, gate modules) and `name — line N` (exports).
    def pairs(title: str, kind: str) -> list[tuple[str, str]] | None:
        lines = _doc_section(text, title)
        if lines is None:
            return None
        out = []
        for line in lines:
            m = re.match(r"- `([^`]+)` — (?:`([^`]+)`|line (\d+))", line)
            if m is None:
                return None
            out.append((m.group(1), m.group(2) if kind == "path" else m.group(3)))
        return out

    def names(title: str) -> list[str] | None:
        lines = _doc_section(text, title)
        if lines is None:
            return None
        out = []
        for line in lines:
            m = re.match(r"- `([^`]+)`", line)
            if m is None:
                return None
            out.append(m.group(1))
        return out

    checks: list[tuple[str, object, object, str]] = []

    documented = pairs("Source Module Files", "path")
    checks.append(
        ("inventory_doc.source_modules", documented,
         sorted(truth["modules"].items()),
         "every .rs under crates/franken-engine/src/ except lib.rs and src/bin/")
    )

    documented = pairs("lib.rs Public Module Exports", "line")
    checks.append(
        ("inventory_doc.lib_exports", documented,
         sorted(((n, str(ln)) for n, ln in truth["exports"]),
                key=lambda e: (e[0], int(e[1]))),
         "`pub mod` lines in lib.rs, with their line numbers")
    )

    documented = pairs("Gate Module Files", "path")
    checks.append(
        ("inventory_doc.gate_modules", documented, sorted(truth["gates"].items()),
         "source modules whose final path segment ends in `_gate`")
    )

    documented = names("Unexported Root Module Files")
    checks.append(
        ("inventory_doc.unexported_root_modules", documented,
         truth["unexported_root_modules"],
         "root modules with no `pub mod` line in lib.rs")
    )

    documented = names("Missing Exported Source Files")
    checks.append(
        ("inventory_doc.missing_export_sources", documented,
         truth["missing_export_sources"],
         "`pub mod` names with no matching root .rs file")
    )

    for key, documented, expected, measure in checks:
        if documented is None:
            parse_failed = True
            rows.append({"surface": key, "status": "unparsed", "measure": measure})
            continue
        documented_sorted = sorted(documented)
        expected_sorted = sorted(expected)
        if documented_sorted == expected_sorted:
            rows.append({"surface": key, "status": "ok", "claimed": len(documented),
                         "measured": len(expected), "measure": measure,
                         "advisory": False})
            continue
        only_doc = [e for e in documented_sorted if e not in expected_sorted]
        only_tree = [e for e in expected_sorted if e not in documented_sorted]
        rows.append({
            "surface": key, "status": "drift", "claimed": len(documented),
            "measured": len(expected), "measure": measure, "advisory": False,
            "in_doc_not_in_tree": [str(e) for e in only_doc[:10]],
            "in_tree_not_in_doc": [str(e) for e in only_tree[:10]],
        })

    # The Summary table is the part a human reads and the part most likely to be
    # hand-patched to "fix" a failing check. Verify it against the lists below it.
    summary_expected = {
        "Source module files": len(truth["modules"]),
        "lib.rs public module exports": len(truth["exports"]),
        "Disabled lib.rs exports": len(truth["disabled"]),
        "Gate module files": len(truth["gates"]),
        "Missing exported source files": len(truth["missing_export_sources"]),
        "Unexported root module files": len(truth["unexported_root_modules"]),
    }
    for label, expected_count in summary_expected.items():
        m = re.search(rf"^\| {re.escape(label)} \| (\d+) \|$", text, re.M)
        key = "inventory_doc.summary." + label.lower().replace(" ", "_").replace(".", "")
        if m is None:
            parse_failed = True
            rows.append({"surface": key, "status": "unparsed",
                         "measure": f"Summary row {label!r}"})
            continue
        claimed = int(m.group(1))
        rows.append({
            "surface": key,
            "status": "ok" if claimed == expected_count else "drift",
            "claimed": claimed, "measured": expected_count,
            "measure": f"Summary row {label!r}", "advisory": False,
        })

    return rows, parse_failed


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Verify README structural-inventory counts against the tree (BRIDGE-00.8)."
    )
    parser.add_argument("--json", dest="json_path", default="")
    parser.add_argument(
        "--fix",
        action="store_true",
        help="rewrite drifted numbers in place (line-count neutral)",
    )
    parser.add_argument("--quiet", action="store_true")
    parser.add_argument(
        "--repo-root",
        default="",
        help="inspect this tree instead of the one containing this script "
        "(used by the negative drill)",
    )
    parser.add_argument(
        "--section",
        choices=("all", "readme", "inventory-doc"),
        default="all",
        help="restrict the checks to one surface (default: all)",
    )
    args = parser.parse_args()

    if args.repo_root:
        set_repo_root(Path(args.repo_root))

    check_readme = args.section in ("all", "readme")
    check_doc = args.section in ("all", "inventory-doc")

    if check_readme and not README.is_file():
        print(f"error: {README} not found", file=sys.stderr)
        return 2

    text = README.read_text() if README.is_file() else ""
    original_line_count = text.count("\n")
    surfaces = measure() if check_readme else []

    rows, unparsed, drifted, advisory_drift = [], [], [], []
    for surface in surfaces:
        match = re.search(surface.pattern, text)
        if match is None:
            unparsed.append(surface.key)
            rows.append(
                {
                    "surface": surface.key,
                    "status": "unparsed",
                    "measured": surface.value,
                    "measure": surface.measure,
                }
            )
            continue

        claimed = int(match.group(1).replace(",", ""))
        matches = claimed == surface.value
        if not matches:
            if surface.advisory:
                advisory_drift.append(surface.key)
            else:
                drifted.append(surface.key)
            if args.fix:
                start, end = match.span(1)
                text = text[:start] + fmt(surface.value) + text[end:]
        rows.append(
            {
                "surface": surface.key,
                "status": "ok" if matches else ("advisory_drift" if surface.advisory else "drift"),
                "claimed": claimed,
                "measured": surface.value,
                "measure": surface.measure,
                "advisory": surface.advisory,
            }
        )

    readme_needs_write = bool(drifted or advisory_drift)

    # The generated inventory doc. Deliberately NOT `--fix`-able: it is generator
    # output, and hand-patching a generated artifact to satisfy a gate is precisely
    # the drift this gate exists to catch. The remedy is to regenerate it with
    # `scripts/generate_architecture_inventory.sh`.
    inventory_rows: list[dict] = []
    inventory_unparsed = False
    if check_doc:
        inventory_rows, inventory_unparsed = check_inventory_doc()
    rows.extend(inventory_rows)
    if inventory_unparsed:
        unparsed.append("inventory_doc")
    inventory_drift = [r["surface"] for r in inventory_rows if r["status"] == "drift"]
    drifted.extend(inventory_drift)

    if args.fix and readme_needs_write:
        if text.count("\n") != original_line_count:
            print(
                "error: --fix would change README line count; refusing, because "
                "docs/claim_to_proof_matrix_v1.json pins claim spans by line number",
                file=sys.stderr,
            )
            return 2
        README.write_text(text)

    report = {
        "schema_version": "franken-engine.readme-inventory-report.v1",
        "owning_bead": "bd-performance-conformance-bridge-tu32j.1.8",
        "summary": {
            "checked": len(rows),
            "ok": sum(1 for r in rows if r["status"] == "ok"),
            "drift": len(drifted),
            "advisory_drift": len(advisory_drift),
            "unparsed": len(unparsed),
            "fix_applied": bool(args.fix and readme_needs_write),
            "inventory_doc_drift": len(inventory_drift),
        },
        "rows": rows,
    }

    if args.json_path:
        out = Path(args.json_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")

    if not args.quiet:
        s = report["summary"]
        print(
            f"readme_inventory=checked={s['checked']} ok={s['ok']} "
            f"drift={s['drift']} advisory_drift={s['advisory_drift']} "
            f"unparsed={s['unparsed']}" + (" fix_applied=1" if s["fix_applied"] else "")
        )
        for row in rows:
            doc_row = row["surface"].startswith("inventory_doc")
            where = "docs/ARCHITECTURE_INVENTORY.md" if doc_row else "README"
            if row["status"] in ("drift", "advisory_drift"):
                # --fix repairs README numbers only; the inventory doc is generated,
                # so saying "corrected" for it would be a lie.
                verb = "corrected" if (args.fix and not doc_row) else f"{where} claims"
                tag = " [advisory]" if row.get("advisory") else ""
                print(
                    f"  {row['surface']}{tag}: {verb} {row['claimed']:,}, measured "
                    f"{row['measured']:,} ({row['measure']})",
                    file=sys.stderr,
                )
                for key, label in (
                    ("in_doc_not_in_tree", "listed but absent from the tree"),
                    ("in_tree_not_in_doc", "present in the tree but unlisted"),
                ):
                    for entry in row.get(key, []):
                        print(f"      {label}: {entry}", file=sys.stderr)
            elif row["status"] == "unparsed":
                print(
                    f"  {row['surface']}: could not locate its {where} row -- the "
                    f"format moved; update the pattern rather than dropping coverage",
                    file=sys.stderr,
                )
        if inventory_drift:
            print(
                "  docs/ARCHITECTURE_INVENTORY.md is generator output; regenerate it "
                "with scripts/generate_architecture_inventory.sh rather than editing "
                "it by hand (--fix deliberately will not touch it)",
                file=sys.stderr,
            )

    # An unparsed row is exit 2, not 1: the gate cannot report drift it can no longer
    # see, and silently checking fewer surfaces is the failure mode this replaces.
    if unparsed:
        return 2
    # `--fix` cannot repair the generated inventory doc, so its drift still fails.
    if inventory_drift:
        return 1
    if drifted and not args.fix:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
