#!/usr/bin/env python3
"""Render a Markdown scoreboard from a test262 ES2020 gate run artifact.

Closes audit findings FIND-6 (`bd-k6n7w`) + FIND-16 (`bd-7ojyd`).

The gate at `scripts/run_test262_es2020_gate.sh` produces three artifacts
per run:

  - `<run_dir>/run_manifest.json`        (top-level v2 schema; bash-emitted)
  - `<run_dir>/test262_runner/<run_id>/run_manifest.json` (per-run counts; runner-emitted)
  - `<run_dir>/test262_runner/<run_id>/test262_hwm.json`  (high-water-mark)

None of them are reviewer-friendly as JSON. This script reads them and
emits a single Markdown document with a scoreboard table and the per-run
metadata.

Usage
-----
    python3 scripts/test262_markdown_scoreboard.py \
        --gate-manifest artifacts/test262_es2020_gate/2026-05-28T09:00:00Z/run_manifest.json \
        --output artifacts/test262_es2020_gate/2026-05-28T09:00:00Z/SCOREBOARD.md

By default the script writes to stdout. With `--update-symlink` it also
updates `<run_dir>/../latest_SCOREBOARD.md` to point at the new file
(useful for CI artifact uploads).

Exit code is non-zero when:

  - the gate outcome is `blocked` (FE-T262-1005 path), OR
  - the runner manifest cannot be located via the gate manifest, OR
  - any required JSON file is unreadable / unparseable.

This script intentionally requires only the Python standard library so
it can run anywhere `python3` is on PATH (CI runners, dev shells, etc.).
"""

from __future__ import annotations

import argparse
import json
import os
import pathlib
import sys
from typing import Any


def read_json(path: pathlib.Path) -> dict[str, Any]:
    try:
        return json.loads(path.read_text())
    except FileNotFoundError as exc:
        sys.exit(f"error: file not found: {path}: {exc}")
    except json.JSONDecodeError as exc:
        sys.exit(f"error: malformed JSON at {path}: {exc}")


def find_runner_manifest(gate_manifest: dict[str, Any]) -> str | None:
    runner_artifacts = gate_manifest.get("runner_artifacts") or {}
    return runner_artifacts.get("runner_manifest")


def find_hwm(gate_manifest: dict[str, Any]) -> str | None:
    runner_artifacts = gate_manifest.get("runner_artifacts") or {}
    return (
        runner_artifacts.get("canonical_high_water_mark")
        or runner_artifacts.get("runner_high_water_mark")
    )


def build_scoreboard(
    gate_manifest_path: pathlib.Path,
    gate_manifest: dict[str, Any],
    runner_manifest: dict[str, Any] | None,
    hwm: dict[str, Any] | None,
) -> str:
    outcome = gate_manifest.get("outcome", "unknown")
    timestamp = gate_manifest.get("timestamp_utc", "unknown")
    mode = gate_manifest.get("mode", "unknown")
    toolchain = gate_manifest.get("toolchain", "unknown")
    failed_command = gate_manifest.get("failed_command") or "—"

    run_id = (runner_manifest or {}).get("run_id", "(no runner manifest)")
    total = (runner_manifest or {}).get("total_profile_tests", 0)
    passed = (runner_manifest or {}).get("passed", 0)
    failed = (runner_manifest or {}).get("failed", 0)
    waived = (runner_manifest or {}).get("waived", 0)
    timed_out = (runner_manifest or {}).get("timed_out", 0)
    crashed = (runner_manifest or {}).get("crashed", 0)
    blocked_failures = (runner_manifest or {}).get("blocked_failures", 0)
    pass_regression_warning = (runner_manifest or {}).get("pass_regression_warning")

    if total > 0:
        pass_rate = passed / total
        pass_rate_pct = f"{pass_rate * 100:.2f}%"
    else:
        pass_rate = None
        pass_rate_pct = "—"

    promotion_threshold = 0.95
    if pass_rate is None:
        promotion_status = "no data"
    elif pass_rate >= promotion_threshold:
        promotion_status = "✓ passes 0.95 threshold"
    else:
        promotion_status = f"✗ below 0.95 threshold ({pass_rate_pct})"

    profile_hash = (runner_manifest or {}).get("profile_hash", "—")
    waiver_hash = (runner_manifest or {}).get("waiver_hash", "—")
    pin_hash = (runner_manifest or {}).get("pin_hash", "—")
    env_fingerprint = (runner_manifest or {}).get("env_fingerprint", "—")

    hwm_pass_count = (hwm or {}).get("pass_count", "—")
    hwm_recorded_at = (hwm or {}).get("recorded_at_utc", "—")
    hwm_profile_hash = (hwm or {}).get("profile_hash", "—")

    lines: list[str] = []
    lines.append("# test262 ES2020 Conformance Scoreboard")
    lines.append("")
    lines.append("> Generated by `scripts/test262_markdown_scoreboard.py` from a")
    lines.append(f"> `scripts/run_test262_es2020_gate.sh` run manifest at")
    lines.append(f"> `{gate_manifest_path}`.")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Field | Value |")
    lines.append("| --- | --- |")
    lines.append(f"| Gate timestamp (UTC) | `{timestamp}` |")
    lines.append(f"| Gate mode | `{mode}` |")
    lines.append(f"| Toolchain | `{toolchain}` |")
    lines.append(f"| Gate outcome | **`{outcome}`** |")
    lines.append(f"| Run id | `{run_id}` |")
    lines.append(f"| Promotion threshold check | {promotion_status} |")
    if failed_command and failed_command != "—":
        lines.append(f"| Failed command | `{failed_command}` |")
    lines.append("")
    lines.append("## Counts")
    lines.append("")
    lines.append("| Metric | Count |")
    lines.append("| --- | ---: |")
    lines.append(f"| Total profile tests | {total} |")
    lines.append(f"| Passed | **{passed}** |")
    lines.append(f"| Failed | {failed} |")
    lines.append(f"| Waived | {waived} |")
    lines.append(f"| Timed out | {timed_out} |")
    lines.append(f"| Crashed | {crashed} |")
    lines.append(f"| Blocked failures | {blocked_failures} |")
    lines.append(f"| **Pass rate** | **{pass_rate_pct}** |")
    if pass_regression_warning:
        lines.append("")
        lines.append(f"⚠ **Pass-regression warning:** {pass_regression_warning}")
    lines.append("")
    lines.append("## Fingerprints")
    lines.append("")
    lines.append("| Field | Value |")
    lines.append("| --- | --- |")
    lines.append(f"| `profile_hash` | `{profile_hash}` |")
    lines.append(f"| `waiver_hash` | `{waiver_hash}` |")
    lines.append(f"| `pin_hash` | `{pin_hash}` |")
    lines.append(f"| `env_fingerprint` | `{env_fingerprint}` |")
    lines.append("")
    lines.append("## High-water mark")
    lines.append("")
    lines.append("| Field | Value |")
    lines.append("| --- | --- |")
    lines.append(f"| HWM pass count | {hwm_pass_count} |")
    lines.append(f"| HWM recorded at | `{hwm_recorded_at}` |")
    lines.append(f"| HWM profile hash | `{hwm_profile_hash}` |")
    if (
        hwm_profile_hash not in (None, "—")
        and profile_hash not in (None, "—")
        and hwm_profile_hash != profile_hash
    ):
        lines.append("")
        lines.append(
            "⚠ **HWM profile_hash drift:** the profile hash recorded in the"
            " high-water mark does not match this run's profile_hash."
            " Either the profile changed (rebake the HWM) or a stale HWM"
            " is being loaded (investigate before promoting)."
        )
    lines.append("")
    lines.append("## Cross-references")
    lines.append("")
    lines.append("- Spec target: `docs/ECMA262_CONFORMANCE_TARGET.md`")
    lines.append("- Aggregate coverage: `docs/conformance/ECMA262_COVERAGE.md`")
    lines.append("- Per-clause traceability: `docs/conformance/SPEC_TO_TEST_TRACEABILITY.md`")
    lines.append("- Per-harness manifest: `crates/franken-engine/docs/CONFORMANCE_HARNESS_MANIFEST.md`")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--gate-manifest",
        required=True,
        type=pathlib.Path,
        help="Path to the gate `run_manifest.json` (v2 schema).",
    )
    parser.add_argument(
        "--output",
        default="-",
        help="Output Markdown path (default: stdout).",
    )
    parser.add_argument(
        "--update-symlink",
        action="store_true",
        help=(
            "Also update `<gate_manifest dir>/../latest_SCOREBOARD.md` to point"
            " at the produced Markdown file (useful for CI artifact uploads)."
        ),
    )
    args = parser.parse_args()

    gate_manifest_path = args.gate_manifest
    gate_manifest = read_json(gate_manifest_path)

    runner_manifest_path = find_runner_manifest(gate_manifest)
    if runner_manifest_path is None:
        print(
            "warning: gate manifest has no runner_artifacts.runner_manifest;"
            " scoreboard counts will be zeroed",
            file=sys.stderr,
        )
        runner_manifest = None
    else:
        runner_manifest = read_json(pathlib.Path(runner_manifest_path))

    hwm_path = find_hwm(gate_manifest)
    hwm = read_json(pathlib.Path(hwm_path)) if hwm_path else None

    markdown = build_scoreboard(gate_manifest_path, gate_manifest, runner_manifest, hwm)

    if args.output == "-":
        sys.stdout.write(markdown)
    else:
        output_path = pathlib.Path(args.output)
        output_path.write_text(markdown)
        print(f"wrote {output_path}", file=sys.stderr)

        if args.update_symlink:
            symlink_path = output_path.parent.parent / "latest_SCOREBOARD.md"
            try:
                if symlink_path.is_symlink() or symlink_path.exists():
                    symlink_path.unlink()
                # Use a path relative to the symlink's parent so the link
                # survives moves of the parent directory.
                relative_target = os.path.relpath(output_path, symlink_path.parent)
                symlink_path.symlink_to(relative_target)
                print(f"updated symlink {symlink_path} -> {relative_target}", file=sys.stderr)
            except OSError as exc:
                print(f"warning: could not update symlink {symlink_path}: {exc}", file=sys.stderr)

    if gate_manifest.get("outcome") == "blocked":
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
